### ISSUE TITLE
Recipe search functionality

### ISSUE THREAD

**Issue by kera-cudmore** [Mbutler1991/seasonedgreetings#10]
Decide on the best way to implement the search functionality

- Discussed that we would like to be global, so using keywords like Christmas could be problematic for people who celebrate alternative holidays e.g. Kwanza etc
- We would like to implement searching by ingredient
- Discussed potential of searching by course (starter, main, dessert, drink) - need to look at API documentation to see if this is feasible

**Comment by Jonathan97-web** [comment]
Search functionality has been implemented to the landing page.

**Comment by Jonathan97-web** [comment]
Closing issue due to being resolved.
