### ISSUE TITLE
Wave empty link error - footer icons

### ISSUE THREAD

**Issue by kera-cudmore** [Mbutler1991/seasonedgreetings#117]
Empty link error on WAVE - I know in the newer versions of font awesome you can add screen reader only spans etc - this will need looking at though for the version of font awesome we're using - 4.7

![Image](https://github.com/Mbutler1991/seasonedgreetings/assets/92253071/6556d384-b179-48b4-b75c-30a4834bc763)

**Comment by emilyrosenberg** [comment]
Requires updating the icon classes
