### ISSUE TITLE
API for Edamam

### ISSUE THREAD

**Issue by kera-cudmore** [Mbutler1991/seasonedgreetings#12]
https://developer.edamam.com/edamam-recipe-api

Little write up needed about the API 

- [x] Why we chose this one over others available - This one had a large database of global recipes, allowed queries by name or ingredient, had a large number of API calls, free for developers :) 
- [x] How to get an api key - instructions

**Comment by Jonathan97-web** [comment]
API key has now been secured, next step is implementation when we start testing to add recipes to our website.

Awaiting other issues to be closed first.

**Comment by Jonathan97-web** [comment]
API has been implemented with mealdb and not edamam for better search functionality as well as unlimited calls to the API.

**Comment by Jonathan97-web** [comment]
Closing issue due to it being resolved.
