### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by kera-cudmore** [Mbutler1991/seasonedgreetings#2]
- [ ] Home Page

**Comment by CaylinDewey** [comment]
![Image](https://github.com/Mbutler1991/seasonedgreetings/assets/139876591/8be7d954-c691-4904-b687-45d197ce46ae)
![Image](https://github.com/Mbutler1991/seasonedgreetings/assets/139876591/0580e036-aca7-431c-b1f1-3a9e27d4a486)
![Image](https://github.com/Mbutler1991/seasonedgreetings/assets/139876591/5997e614-da27-4bc9-b5ee-88996afc6416)
![Image](https://github.com/Mbutler1991/seasonedgreetings/assets/139876591/581c9cc5-8fbf-416d-b738-05e03d50dc47)
